using CryptoTracker.WPF.Models;

namespace CryptoTracker.WPF.Helpers.Constants
{
    internal static class CurrencyCatalog
    {
        public static readonly List<Currency> All = new()
        {
            new Currency("usd", "US Dollar"),
            new Currency("eur", "Euro"),
            new Currency("uah", "Ukrainian Hryvnia"),
            new Currency("btc", "Bitcoin"),
            new Currency("eth", "Ethereum"),
            new Currency("ltc", "Litecoin"),
            new Currency("bch", "Bitcoin Cash"),
            new Currency("bnb", "Binance Coin"),
            new Currency("eos", "EOS"),
            new Currency("xrp", "XRP"),
            new Currency("xlm", "Stellar"),
            new Currency("link", "Chainlink"),
            new Currency("dot", "Polkadot"),
            new Currency("yfi", "Yearn Finance"),
            new Currency("aed", "UAE Dirham"),
            new Currency("ars", "Argentine Peso"),
            new Currency("aud", "Australian Dollar"),
            new Currency("bdt", "Bangladeshi Taka"),
            new Currency("bhd", "Bahraini Dinar"),
            new Currency("bmd", "Bermudian Dollar"),
            new Currency("brl", "Brazilian Real"),
            new Currency("cad", "Canadian Dollar"),
            new Currency("chf", "Swiss Franc"),
            new Currency("clp", "Chilean Peso"),
            new Currency("cny", "Chinese Yuan"),
            new Currency("czk", "Czech Koruna"),
            new Currency("dkk", "Danish Krone"),
            new Currency("gbp", "British Pound"),
            new Currency("gel", "Georgian Lari"),
            new Currency("hkd", "Hong Kong Dollar"),
            new Currency("huf", "Hungarian Forint"),
            new Currency("idr", "Indonesian Rupiah"),
            new Currency("ils", "Israeli Shekel"),
            new Currency("inr", "Indian Rupee"),
            new Currency("rub", "Russian Ruble"),
            new Currency("jpy", "Japanese Yen"),
            new Currency("krw", "South Korean Won"),
            new Currency("kwd", "Kuwaiti Dinar"),
            new Currency("lkr", "Sri Lankan Rupee"),
            new Currency("mmk", "Myanmar Kyat"),
            new Currency("mxn", "Mexican Peso"),
            new Currency("myr", "Malaysian Ringgit"),
            new Currency("ngn", "Nigerian Naira"),
            new Currency("nok", "Norwegian Krone"),
            new Currency("nzd", "New Zealand Dollar"),
            new Currency("php", "Philippine Peso"),
            new Currency("pkr", "Pakistani Rupee"),
            new Currency("pln", "Polish Zloty"),
            new Currency("sar", "Saudi Riyal"),
            new Currency("sek", "Swedish Krona"),
            new Currency("sgd", "Singapore Dollar"),
            new Currency("thb", "Thai Baht"),
            new Currency("try", "Turkish Lira"),
            new Currency("twd", "Taiwan Dollar"),
            new Currency("vef", "Venezuelan Bolívar"),
            new Currency("vnd", "Vietnamese Dong"),
            new Currency("zar", "South African Rand"),
            new Currency("xdr", "IMF Special Drawing Rights"),
            new Currency("xag", "Silver (troy ounce)"),
            new Currency("xau", "Gold (troy ounce)"),
            new Currency("bits", "Bitcoin Bits (μBTC)"),
            new Currency("sats", "Satoshis")
        };
    }
}
